### ISSUE TITLE
Invalid Yaml syntax on require_tests rule

### ISSUE THREAD

**Issue by nWidart** [VarCI/support#6]
Hello,

I'm getting a warning from Sensiolabs Insights that the following rule isn't valid yaml syntax:

``` yaml
require_tests:
    name: Require unit tests for pull requests
    events: pull_request
    when:
    - action = "opened"
    - count(filter(files, "[name=/^src\/]")) > 1
    - count(filter(files, "[name=/^tests\/]")) = 0
    message: "@{{ user.login }}, remember that all pull requests should be accompanied
      with unit tests per our contributing guidelines. Please `/cc` one of our maintainers
      if you need help with this!"
```

With the following error:

```
Error : Malformed inline YAML string ("@{{ user.login }}, remember that all pull requests should be accompanied) at line 8 (near "message: "@{{ user.login }}, remember that all pull requests should be accompanied").
Line : 8  message: "@{{ user.login }}, remember that all pull requests should be accompanied
```

Also tested here http://codebeautify.org/yaml-validator

Thanks
